### ISSUE TITLE
Porting MODEX optimizations to v3.x series

### ISSUE THREAD

**Issue by karasevb** [openpmix/openpmix#1169]
Since the MODEX optimizations (#1152, #1149, #1125) are merged to master, we would like to port those to the nearest release branch. 
What are the steps to open a new branch v3.2? 
Port of all PRs is ready, once new branch appears I'll open PRs against it.

@rhc54 @jjhursey @artpol84 

PRs which should be ported:
- [x]  bfrops: redefinition regtypes for internal usage #1144 (done: https://github.com/pmix/pmix/pull/1173)
- [x] modex: optimization of rank identification size reduction #1125 (done: #1174)
- [x] modex: reduce modex size by replacing key names with indexes #1149 (done: #1175)
- [x] Flexible integer packing with `psquash` framework in `bfrops` v4 #1152 (done: #1176)

**Comment by jjhursey** [comment]
For now, just PR them against the `v3.1` branch (which would be used as the base for a `v3.2`), then we can change the base of the PR on GitHub once a `v3.2` branch is created.

**Comment by artpol84** [comment]
Thanks!
@karasevb, please proceed. And pick a today’s fix from @jjhursey for MAC: https://github.com/pmix/pmix/pull/1171

**Comment by jjhursey** [comment]
Probably also want PR #1168 which is a bit of cleanup for the argv.c file related to PR #1149.

**Comment by karasevb** [comment]
Since bfrops v4 (which has been modified) is not present in PMIx v3, and new features require to add with new bfrops, so the question is: which version of bfrops required to introduce for PMIx v3? Bfrops v31 or v32?

**Comment by karasevb** [comment]
I’ve currently added bfrops v32, but if it’s not OK, I’ll change the version.

**Comment by jjhursey** [comment]
For PR #1176 I think it's ok for now to keep it at v32 as we discuss the best path forward there. I need to think about it a bit more. Let's make sure to discuss it on the call this week.

Since these optimizations are targeted at v3.2, it shouldn't hold up the pending v3.1.x bug fix release.

**Comment by jjhursey** [comment]
Per teleconf:
 * Split these into two sets targeted at two different release points divided by the cross-version impact.
 * 3.1.4
   - modex: optimization of rank identification size reduction #1125 (done: #1174)
   - modex: reduce modex size by replacing key names with indexes #1149 (done: #1175)
 * 3.2
   - bfrops: redefinition regtypes for internal usage #1144 (done: #1173)
   - Flexible integer packing with psquash framework in bfrops v4 #1152 (done: #1176)

**Comment by jjhursey** [comment]
I don't know if PR #1322 needs to be incorporated here or not.

**Comment by jjhursey** [comment]
Per teleconf:
 * We may not end up releasing a v3.2 and instead wait for v4.0 to release this feature.
 * For now, we will keep the existing branch (even though it is out of sync with v3.1) just in case we need to adjust this plan.

**Comment by rhc54** [comment]
A v3.2 branch has been created that contains these updates - we will not be bringing them back into the v3.1 series
