### ISSUE TITLE
PMIx v3.2.0 Checklist

### ISSUE THREAD

**Issue by rhc54** [openpmix/openpmix#1352]
## Build the Release
- [x] Verify the major,minor,release,greek version numbers in `VERSION`
- [x] Update the `c:r:a` shared library version number(s) in `VERSION` [per the GNU Libtool shared library version number rules](https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html)
   - **NOTE:** It may be helpful to use a command like `git checkout BRANCH; git pull --rebase; git log --stat --topo-order --decorate TAG_FROM_PREVIOUS_RELEASE..HEAD` to examine the Git logs and see what has changed.
   - [ ] *IF RELEVANT:* If this is a new backwards-compatible release on a single branch (i.e., this is `vx.y.z` where `z>1`), you probably want to examine `git log --stat --no-merges last_release_tag..this_branch_name` to see what source code files have changed (which directly impacts how to increment the `c:r:a` values).
  - [ ] *IF RELEVANT:* If this is a new release series (e.g., `vx.y.0`), set `r` to 0 and increase `c` values by 10 compared to the first release in the prior series (i.e., `vx.(y-1).0` or `v(x-1).0.0`, as relevant).
  - [ ] *IF RELEVANT:* If this is a new backwards-compatible release series (i.e., `vx.y.0`, where `y>1`), set`a` values to 10 so that the shared libraries will be ABI compatible with the prior release series.
  - [ ] *IF RELEVANT:* If this is a new backwards-**IN**compatible release series (i.e., `vx.0.0`), set `a` values to 0 so that there is no possibility of users accidentally mixing shared library versions.
- [x] Update all documentation files (especially including dates and version numbers), including:
  - [ ] `README`: all relevant updates, build options, etc.  Be sure to update the date near the top of the file.
  - [x] `NEWS`: List all user-noticeable changes.  Similar to setting shared library versions (above): 
       - Pro tip: if this is a new release on a single branch (i.e., this is `vx.y.z` where `z>1`), you probably want to examine `git log --stat --no-merges last_release_tag..this_branch_name` to see what has changed.
       - Pro tip: if this is a new release series (i.e., this is `vx.y.0` where `y>1`, or this is `vx.0.0`), you will need to be more creative in examining the git logs because this release is on a different branch than the prior release (`vx.(y-1).z`).  Hence, `git log ... last_release_tag..this_branch_name` will not necessarily give you need.  You may need to merge what has changed on your branch with what has changed on the prior release branch, depending on when the prior release branched from this branch.  Read the **SPECIFYING RANGES** section `gitrevisions(7)` for more details.
  - [ ] `LICENSE`: Update the years in the copyright notices 
- [x] Create a tag for the release, matching the version being released (ie, `git tag -a v3.0.1 <HASH>`).  Verify <HASH> points to the correct release point.  Push the tag for the release.
- [x] Run xversion and verify cross-version compatibility
- [ ] PR release candidate to OMPI for MTT and verify passage (must run for at least one week for coverage)
- [x] Build the tarball

## Publish the release
- [ ] Update the web site blog announcing the release
  - [ ] Verify the live web site to ensure announcement is present
- [x] Close the relevant Github milestone in `pmix/pmix`
- [x  Send an email to the `pmix@googlegroups.com` mailing list announcing the release

## Prep for next release in series
- [x] Re-target (change milestone) all still-open issues for the new release to the next major or minor release of PMIx as appropriate
- [x] Ensure that new Github milestones exist in [GitHub](https://github.com/pmix/pmix/issues) for the next release
- [ ] Update the PMIx version number in `VERSION` to `<NEXT_VERSION>` and set `greek` to `a1`
- [ ] Open a duplicate of this issue for the next release in this series.

**Comment by jjhursey** [comment]
Per teleconf
 * We have put v3.2 on hold to focus on v4.0 release.
 * We can keep this ticket open in case we need to revisit that decision.

**Comment by FaDee1** [comment]
> ## สร้างการเปิดตัว
> * [ ]  ตรวจสอบหมายเลขรุ่นหลักรุ่นย่อยรุ่นกรีก `VERSION`
> * [ ] อัปเดต`c:r:a`หมายเลขเวอร์ชันของไลบรารีที่แบ่งใช้ในกฎหมายเลขเวอร์ชันไลบรารีที่แบ่งใช้`VERSION` [ของ GNU Libtool](https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html)
>   
>   * **หมายเหตุ:**อาจเป็นประโยชน์ในการใช้คำสั่งเช่น`git checkout BRANCH; git pull --rebase; git log --stat --topo-order --decorate TAG_FROM_PREVIOUS_RELEASE..HEAD`ตรวจสอบบันทึก Git และดูว่ามีอะไรเปลี่ยนแปลง
>   * [ ]  _ถ้ามี:_ในกรณีนี้คือการเปิดตัวใหม่ย้อนหลังได้ในสาขาเดียว (เช่นนี้เป็น`vx.y.z`ที่`z>1`) คุณอาจต้องการที่จะตรวจสอบ`git log --stat --no-merges last_release_tag..this_branch_name`เพื่อดูว่าไฟล์รหัสต้นฉบับมีการเปลี่ยนแปลง (ซึ่งผลกระทบโดยตรงต่อวิธีการที่จะเพิ่มขึ้น`c:r:a`ค่า)
>   * [ ]  _หากเกี่ยวข้อง:_หากนี่เป็นซีรีส์ใหม่ (เช่น, `vx.y.0`) ให้ตั้งค่า`r`เป็น 0 และเพิ่ม`c`ค่า 10 โดยเทียบกับรีลีสแรกในซีรีส์ก่อนหน้า (เช่น`vx.(y-1).0`หรือ`v(x-1).0.0`ที่เกี่ยวข้อง)
>   * [ ]  _หากเกี่ยวข้อง:_หากนี่เป็นซีรีส์รีลีสที่เข้ากันได้แบบย้อนหลัง (เช่น`vx.y.0`ที่ที่`y>1`) ให้ตั้ง`a`ค่าเป็น 10 เพื่อให้ไลบรารีที่ใช้ร่วมกันจะเข้ากันได้กับ ABI กับซีรีส์รุ่นก่อนหน้า
>   * [ ]  _ถ้ามี:_ถ้าเป็น backwards- ใหม่**ใน**ซีรีส์เปิดตัวเข้ากันได้ (เช่น`vx.0.0`) ตั้ง`a`ค่าเป็น 0 เพื่อให้มีความเป็นไปได้ของผู้ใช้ที่ใช้ร่วมกันโดยบังเอิญผสมรุ่นห้องสมุดไม่มี
> * [ ]  อัปเดตไฟล์เอกสารทั้งหมด (โดยเฉพาะรวมถึงวันที่และหมายเลขเวอร์ชั่น) รวมถึง:
>   
>   * [ ]  `README`: การอัปเดตที่เกี่ยวข้องทั้งหมดตัวเลือกการสร้าง ฯลฯ อย่าลืมอัปเดตวันที่ใกล้กับด้านบนของไฟล์
>   * [ ]  `NEWS`: แสดงการเปลี่ยนแปลงทั้งหมดที่ผู้ใช้สังเกตเห็น คล้ายกับการตั้งค่าเวอร์ชันไลบรารีที่แชร์ (ด้านบน):
>     
>     * เคล็ดลับสำหรับมืออาชีพ: หากนี่เป็นรุ่นใหม่ในสาขาเดียว (เช่นนี้คือ`vx.y.z`ที่`z>1`) คุณอาจต้องการตรวจสอบ`git log --stat --no-merges last_release_tag..this_branch_name`เพื่อดูว่ามีการเปลี่ยนแปลงอย่างไร
>     * เคล็ดลับสำหรับมืออาชีพ: หากนี่เป็นซีรี่ส์รีลีสใหม่ (เช่นนี่คือ`vx.y.0`ที่`y>1`หรือนี่คือ`vx.0.0`) คุณจะต้องมีความคิดสร้างสรรค์มากขึ้นในการตรวจสอบบันทึก git เพราะรีลีสนี้อยู่ในสาขาที่แตกต่างจากรีลีสก่อนหน้านี้ ( `vx.(y-1).z`) ดังนั้น`git log ... last_release_tag..this_branch_name`จะไม่จำเป็นต้องให้คุณต้องการ คุณอาจจำเป็นต้องรวมสิ่งที่มีการเปลี่ยนแปลงในสาขาของคุณกับสิ่งที่มีการเปลี่ยนแปลงในสาขาที่วางจำหน่ายก่อนหน้าขึ้นอยู่กับเมื่อรุ่นก่อนหน้าแยกออกจากสาขานี้ อ่าน**ระบุช่วง**ส่วน`gitrevisions(7)`สำหรับรายละเอียดเพิ่มเติม
>   * [ ]  `LICENSE`: อัพเดทปีในประกาศลิขสิทธิ์
> * [ ]  Create a tag for the release, matching the version being released (ie, `git tag -a v3.0.1 <HASH>`).  Verify  points to the correct release point.  Push the tag for the release.
> * [ ]  Run xversion and verify cross-version compatibility
> * [ ]  PR release candidate to OMPI for MTT and verify passage (must run for at least one week for coverage)
> * [ ]  Build the tarball
> 
> ## Publish the release
> * [ ]  Update the web site blog announcing the release
>   
>   * [ ]  Verify the live web site to ensure announcement is present
> * [ ]  Close the relevant Github milestone in `pmix/pmix`
> * [x  Send an email to the `pmix@googlegroups.com` mailing list announcing the release
> 
> ## Prep for next release in series
> * [ ]  Re-target (change milestone) all still-open issues for the new release to the next major or minor release of PMIx as appropriate
> * [ ]  Ensure that new Github milestones exist in [GitHub](https://github.com/pmix/pmix/issues) for the next release
> * [ ] อัปเดตหมายเลขเวอร์ชัน PMIx `VERSION`เป็น`<NEXT_VERSION>`และตั้งค่า`greek`เป็น`a1`
> * [ ]  เปิดซ้ำของปัญหานี้สำหรับรุ่นถัดไปในชุดนี้

MO

**Comment by rhc54** [comment]
I'm sorry - can you please translate your additions into English and re-edit them? We cannot understand what you are posting

**Comment by jjhursey** [comment]
This has now been released.
