### ISSUE TITLE
Checklist for "stable" landing point

### ISSUE THREAD

**Issue by rhc54** [openpmix/openpmix#3409]
With the project winding down, it is time to define a stable landing point where we can leave it for those wanting to use it. This means:

* removing all stale code, particularly components that aren't actively used
* collapsing frameworks into single code directories where multiple variations are not required (e.g., rtc)
* reducing complexity wherever possible

We'll keep a checklist here as we work thru the process - will culminate in a new PMIx v6 release series

Code pruning and correction

- [x] Collapse "pfexec" framework
- [x] Resolve future of "pgpu" framework - DEFAULT: removal
        * Under consideration
        * RETAIN - MAY BE USEFUL TO SCHEDULER WORK
- [x] Consider removal of "mpich" and "oshmem" components in "pmdl" framework - DEFAULT: removal
        * Check with those communities - REMOVED
- [x] Resolve future of "pnet" framework - DEFAULT: removal
        * Still need OmniPath token generation? Do Intel or Cornelis care? YES - RETAIN framework
- [x] Resolve future of "prm" framework - DEFAULT: removal
        * Might provide a means for interacting with existing schedulers - e.g., via REST. Under consideration
        * REMOVED
- [x] Resolve future of "psensor" framework - DEFAULT: removal
        * Pondering - probably remove
        * RETAIN FOR NOW
- [x] Consolidate "psquash" into base modex support and remove framework
        * Consider removal of psquash functionality in favor of simple compression
        * FUNCTIONALITY CANNOT BE REMOVED - BREAKS XVERSION SUPPORT
        * Framework was consolidated into base code
- [x] Resolve future of "pstat" framework - DEFAULT: removal
        * Under consideration - Aurelien might know some interested people
        * RETAIN FOR NOW
- [x] Resolve future of "pstrg" framework - DEFAULT: removal
        * Remove - done in #3412 
- [x] Resolve existing issues - ALL RESOLVED
        * https://github.com/openpmix/prrte/issues/1773
        * https://github.com/openpmix/openpmix/issues/3360
- [x] Raise min HWLOC version to 2.1.0

Enhancements
- [ ] Implement missing Python bindings

Scheduler integration
- [ ] Complete implementation of related APIs

**Comment by rhc54** [comment]
Declaring this complete. There have been a number of bugs identified and fixed, including revamp of PMIx_Resolve_xxx and PMIx_Query_info functions to properly handle a complete range of situations. While we haven't completely finished the identified extensions/enhancements, I think we can declare ourselves to be at a stable stopping point.
